# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20160718_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='time_zone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Time Zone'),
        ),
    ]
