# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 12:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_auto_20160719_1151'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tokens',
            new_name='Token',
        ),
    ]
